model:
  name: RDNet
  backbone:
    - name: cbs
      out: 64
    - name: cbs
      out: 128
    - name: downsample
      stride: 2
    - name: csp
      out: 256
      n: 1
      shortcut: True


data:
  data_root: /home/nju-student/mkh/datasets/radar/MTD_Results
  val_ratio: 0.2
  shuffle: True


train:
  batch_size: 16
  num_workers: 4
  num_epochs: 100
  lr: 0.001
  height: 32
  width: 900
  num_classes: 6
  channels: 1
  lr_scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
  optimizer:
    name: SGD
    momentum: 0.9
    weight_decay: 0.0005
  loss:
    name: FocalLoss
    gamma: 2.0

