model:
  name: SwinTransformer
  patch_height: 2
  patch_width: 34
  embed_dim: 96
  depths: [2, 2]
  heads: [3, 6]
  window_size: 4
  ff_ratio: 4.0
  qkv_bias: True
  dropout: 0.
  attn_dropout: 0.
  dropout_path: 0.1
  norm: LayerNorm
  patch_norm: True
  ape: False


data:
  data_root: E:/DataSets/挑战杯_揭榜挂帅_CQ-08赛题_数据集/MTD_Results
  val_ratio: 0.2
  shuffle: True


train:
  batch_size: 16
  num_workers: 4
  num_epochs: 100
  lr: 0.001
  height: 32
  width: 544
  num_classes: 6
  channels: 1
  lr_scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.000001
  optimizer:
    name: SGD
    momentum: 0.9
    weight_decay: 0.0005
  loss:
    name: FocalLoss
    gamma: 2.0

